-- ============================================================================
-- 06_ML_MODELS.SQL — ML Functions for Precision Agriculture & Yield Forecasting
-- ============================================================================
USE DATABASE PALM_OIL_PRECISION_AG;
USE SCHEMA ML;

-- ML.FORECAST: FFB_YIELD_FORECAST_MODEL
CREATE OR REPLACE SNOWFLAKE.ML.FORECAST ML.FFB_YIELD_FORECAST_MODEL(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.YIELD_TIMESERIES'),
  SERIES_COLNAME => 'ESTATE_ID',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y'
  
);

CREATE OR REPLACE TABLE ML.FFB_YIELD_FORECAST_MODEL_RESULTS AS
SELECT * FROM TABLE(ML.FFB_YIELD_FORECAST_MODEL!FORECAST(FORECASTING_PERIODS => 14));

-- ML.ANOMALY_DETECTION: PEST_DISEASE_ANOMALY_MODEL
CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION ML.PEST_DISEASE_ANOMALY_MODEL(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.SOIL_HEALTH_INDEX'),
  SERIES_COLNAME => 'ESTATE_ID',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y',
  LABEL_COLNAME => ''
);

CREATE OR REPLACE TABLE ML.PEST_DISEASE_ANOMALY_MODEL_RESULTS AS
SELECT * FROM TABLE(ML.PEST_DISEASE_ANOMALY_MODEL!DETECT_ANOMALIES(INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.SOIL_HEALTH_INDEX'), SERIES_COLNAME => 'ESTATE_ID', TIMESTAMP_COLNAME => 'DS', TARGET_COLNAME => 'Y'));

