-- ============================================================================
-- 99_RESET.SQL — Reset Precision Agriculture & Yield Forecasting to clean demo state
-- ============================================================================
USE DATABASE PALM_OIL_PRECISION_AG;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_INGEST_SENSORS SUSPEND;
ALTER TASK IF EXISTS APP.TASK_RETRAIN_MODELS SUSPEND;
ALTER TASK IF EXISTS APP.TASK_ANALYZE_IMAGERY SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.ESTATE_YIELD_SUMMARY REFRESH;
ALTER DYNAMIC TABLE CURATED.YIELD_TIMESERIES REFRESH;
ALTER DYNAMIC TABLE CURATED.SOIL_HEALTH_INDEX REFRESH;
ALTER DYNAMIC TABLE CURATED.PEST_DISEASE_ALERTS REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM PALM_OIL_PRECISION_AG.RAW.ESTATES → 50
-- SELECT COUNT(*) FROM PALM_OIL_PRECISION_AG.RAW.SENSOR_READINGS → 200000
-- SELECT COUNT(*) FROM PALM_OIL_PRECISION_AG.RAW.HARVEST_RECORDS → 100000

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_ANALYZE_IMAGERY RESUME;
ALTER TASK IF EXISTS APP.TASK_RETRAIN_MODELS RESUME;
ALTER TASK IF EXISTS APP.TASK_INGEST_SENSORS RESUME;
